Cellular: Error handling for socket create
u-blox/mbed-os pull request #13
Opened 2018-10-05 12:38 UTC by mudassar-ublox

### Description
In UBLOX_AT_CellularStack, Added error handling for `create_socket_impl`. 

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Breaking change

2018-10-07 23:21 UTC, RobMeades requested changes
A few minor suggestions for tidy ups.

2018-10-07 23:21 UTC, RobMeades commented on features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
>      _at.unlock();
I think the `_at` lock should extend across the calls to `_at.get_last_error()` otherwise we can't be sure that the last error was due to this code or some `_at` calls in a parallel thread.

2018-10-07 23:21 UTC, RobMeades commented on features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
> +    if (_at.get_last_error() != NSAPI_ERROR_OK || sock_id == -1) {
Better to fully bracket this: `if ((_at.get_last_error() != NSAPI_ERROR_OK) || (sock_id == -1)) {`

2018-10-08 07:31 UTC, mudassar-ublox commented
Updated. 
@RobMeades Please review now.

2018-10-10 16:02 UTC, RobMeades approved these changes
Looks good to me.

2018-10-17 08:02 UTC, merged