Cellualr: corrected credentials check
u-blox/mbed-os pull request #7
Opened 2018-06-12 10:01 UTC by mudassar-ublox

### Description
This pull request fix the wrong check on credentials, _uname, _pwd and _apn.

"if (_uname)" is checking address, which is true and freeing uninitialized pointer causing  MbedOS Fault Handler. Instead of checking address, check content if content is present then free.

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] New target
    [ ] Feature
    [ ] Breaking change

2018-06-19 13:01 UTC, mudassar-ublox commented
Hi @RobMeades, Please review this pull request after that I will generate pull request to arm/mbed-os.

2018-06-20 09:34 UTC, RobMeades commented
Hmmm.  This doesn't look right to me.  `_uname` is a pointer to an array of `char`.  in `AT_CellularNetwork.cpp`, `set_credentials()`, memory is `malloc()`ed and the pointer assigned to `_uname`:

```
_uname = (char *)malloc(len * sizeof(char) + 1);
```
So the original check is correct, if `_uname` is not `NULL` then it should be `free()`'d. I think the problem is that, after the line `free(_uname)`, `_uname` is not set to `NULL`; without this it could be `free()`'d twice. In other words the code should read:

```
    if (_uname) {
        free(_uname);
        _uname = NULL;
    }
```

2018-06-20 09:35 UTC, RobMeades requested changes
See comment.

2018-06-20 10:38 UTC, mudassar-ublox commented
`set_credentials(apn, uname, pwd)` function is only called when APN is not NULL. So, this is not called in case when APN is NULL:
 `_uname = (char *)malloc(len * sizeof(char) + 1); `

And in this scenario, _uname is probably a dangling pointer and freeing it results in a Hard Fault. The hard fault occurs the first time so even if we do this: `_name = NULL` after freeing, the problem is still there.

2018-06-20 10:58 UTC, RobMeades commented
When `AT_CellularNetwork` is instantiated it sets `_uname` to `NULL`, so that should not be possible.  Can you do some checking on its value at various points in the execution of your scenario?

2018-06-20 11:08 UTC, mudassar-ublox commented
Yes, you are right. Found the exact problem. In our API, `get_next_credentials` function is setting `_uname ` empty if it is NULL.
`_uname  = (char*)(_uname   ?  _uname  : ""); `

Will remove that check from api and no need for this pull request now, will close it.

2018-06-20 11:11 UTC, closed without merging